// Package main implements tfwatch, a CLI tool that extracts Terraform
// dependency metadata (modules, providers, and backend configuration) and
// publishes it as OpenTelemetry metrics.
//
// tfwatch parses the files generated by "terraform init" — modules.json,
// .terraform.lock.hcl, and *.tf backend blocks — to build a dependency
// inventory without executing Terraform itself.
//
// Usage:
//
//	# List detected dependencies
//	tfwatch --list --dir ./infra
//
//	# Publish metrics to an OTEL collector
//	tfwatch --dir ./infra --otel-endpoint otel.example.com:4317
//
//	# Show version
//	tfwatch --version
package main
