// Package tfwatch extracts Terraform dependency metadata (modules, providers,
// and backend configuration) and publishes it as OpenTelemetry metrics.
//
// It parses the files generated by "terraform init" — modules.json,
// .terraform.lock.hcl, and *.tf backend blocks — to build a dependency
// inventory without executing Terraform itself.
package tfwatch
