name: Bug Report
description: Report a bug in tfwatch
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Run `tfwatch --dir ./my-repo`
        2. ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: tfwatch version
      description: Output of `tfwatch --version`
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 14.2, Ubuntu 24.04, etc."
    validations:
      required: true

  - type: input
    id: terraform
    attributes:
      label: Terraform version
      description: Output of `terraform version`
      placeholder: "1.9.8"

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      render: shell
